name: repeater
description: "An app to assist hafiz in scheduling timetables."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flex_color_picker: ^3.6.0
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_html_video: ^3.0.0-beta.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  # isar_flutter_libs: ^4.0.0-dev.3
  # path_provider: ^2.1.4
  photo_view: ^0.15.0
  provider: ^6.1.2

dev_dependencies:
  analyzer: ^6.7.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

# dependency_overrides:
#   collection: ^1.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
