name: repeater
description: "An app to assist hafiz in scheduling timetables."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_html_video: ^3.0.0-beta.2
  http: ^1.2.2
  photo_view: ^0.15.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
