name: repeater
description: "An app to assist hafiz Quran in scheduling timetables."
publish_to: 'none'
version: 0.2.1

environment:
  sdk: ^3.5.1

dependencies:
  awesome_notifications: ^0.10.0
  awesome_notifications_core: ^0.10.0
  confetti: ^0.8.0
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_html_video: ^3.0.0-beta.2
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  intl: ^0.20.2
  photo_view: ^0.15.0
  provider: ^6.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  analyzer: ^6.7.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon/
